### ISSUE TITLE
__cpp_lib_three_way_comparison is not defined in clang 8 or 9

### ISSUE THREAD

**Issue by grattle** [tzlaine/stl_interfaces#1]
iterator_interface.hpp doesn't compile on my clang 8.

As a local kludge, I just renamed all references  to __cpp_lib_three_way_comparison with a legal #define variable set to 0

Great iterator interface, I love it!

Arthur

**Comment by tzlaine** [comment]
Thanks!  The pattern __foo is reserved by the standard, and in particular a macro that starts with that (or is it "__cpp" -- I forget) is supposed to evaluate to false if the compiler has never seen that macro.  This is to make checks for such macros well-formed under versions of C++ from before they were introduced.  This also passes the tests in Travis.  Are you possibly running an oddly=configured build?

**Comment by grattle** [comment]
On Tuesday, 17 December 2019 11:46:11 AM AEDT Zach Laine wrote:


Thanks! The pattern __foo is reserved by the standard, and in particular a macro that starts 
with that (or is it "__cpp" -- I forget) is supposed to evaluate to false if the compiler has 
never seen that macro. This is to make checks for such macros well-formed under versions 
of C++ from before they were introduced. This also passes the tests in Travis. Are you 
possibly running an oddly=configured build? 

Yes, others have said I am odd...

../stl_interfaces/iterator_interface.hpp:13:16: error: '__cpp_lib_three_way_comparison' is 
not defined, evaluates to 0 [-Werror,-Wundef]

So, I could add -Wno_undef to my compile line. But that error line perhaps implies a naked 
__cpp_lib_three_way_comparison may be deprecated, or it could be a clang thing.

In my little world, I'm lucky the only macro I need is #if NDEBUG, so I have thankfully 
forgotten all about them and where they fit in the evolving Standard.

Again, these are all tiny issues. I do love how you have factored out much of the drudgery 
in making iterators. It is now permanently in my toolkit.

Many thanks,


Arthur

**Comment by tzlaine** [comment]
Ok, thanks for clarifying.  I'll probably just add a defined() around those so that users with those flags are not caught in pointless compilation errors.
