### ISSUE TITLE
Compile error in VS2015 (msvc 19.0.3) due to issues with noexcept() operator in function overloading

### ISSUE THREAD

**Issue by badair** [tzlaine/stl_interfaces#16]
From https://lists.boost.org/Archives/boost/2019/12/247907.php

**Comment by DanielaE** [comment]
This might actually be a bug in msvc 14.0!

**Comment by tzlaine** [comment]
Then I guess VS 2015 is not supported.  STLInterfaces works "with any conforming C++14 compiler."
