### ISSUE TITLE
Remove usage of non-existent v2_dtl members in container_interface.hpp

### ISSUE THREAD

**Issue by badair** [tzlaine/stl_interfaces#22]
From https://lists.boost.org/Archives/boost/2019/12/247907.php

**Comment by tzlaine** [comment]
I'm going to consider this moot for now, since all that code (the never-compiled C++20 implementation sketch) is going away for the first Boost release anyway.  It will come back when there is at least one C++20 implementation that works.

**Comment by tzlaine** [comment]
Never mind.  This was so easy, I just did it.
