### ISSUE TITLE
Consider documenting signatures and return types of functions provided by base class templates

### ISSUE THREAD

**Issue by badair** [tzlaine/stl_interfaces#23]
This would take a lot of work, but it would be really nice (even for iterators, where this info is implied by the category).

**Comment by tzlaine** [comment]
Would it be enough to point to the relevant part of the standard?  These are all documented on eel.is and cppreference.com.

**Comment by badair** [comment]
That would be nice, but I think it would be ideal for the library to document this explicitly too. If the boost library gets out of sync with the standard someday, it would be nice for the documentation to make the discrepancies more obvious. Maybe overkill.
