### ISSUE TITLE
Make use of __has_include conditional

### ISSUE THREAD

**Issue by DanielaE** [tzlaine/stl_interfaces#32]
E.g. from `fwd.h` lines 11-14:

```
#if 201703L <= __cplusplus && __has_include(<stl2/ranges.hpp>) && \
    !defined(BOOST_STL_INTERFACES_DISABLE_CMCSTL2)
#include <stl2/ranges.hpp>
#endif
```

If a compiler doesn't implement _has-include-expressions_ [`has_include()`](http://eel.is/c++draft/cpp#nt:has-include-expression) from C++ 17, then it will complain about unexpected _pp-tokens_ when processing line 11 in phase 4. Therefore change the code from the example like so:

```
#if 201703L <= __cplusplus && defined(__has_include)
#if	__has_include(<stl2/ranges.hpp>) && \
    !defined(BOOST_STL_INTERFACES_DISABLE_CMCSTL2)
#include <stl2/ranges.hpp>
#endif
#endif
```

**Comment by tzlaine** [comment]
Fixed.  Thanks, Daniela.
